@startuml
class Administracion.AdministracionController
class Administracion.AdministracionMain
class BBDDRural.BBDDController
class BBDDRural.BackupDatabase
class BBDDRural.RestoreDatabase
class Clientes.ClienteDAO
class Clientes.ClientesClass
class Clientes.ClientesControlador
class Clientes.ClientesMain
class Clientes.TextFieldLimitador
class Habitaciones.ConsultasHabitaciones
class Habitaciones.Habitacion
class Habitaciones.HabitacionesController
class Habitaciones.HabitacionesMain
class Inicio.InicioController
class Inicio.InicioMain
class Login.LoginController
class Login.LoginMain
class Reservas.Habitacion
class Reservas.ReservasController
class Reservas.ReservasMain
class RestoreHotelRural.RestoreDataBaseCont
class RestoreHotelRural.RestoreDatabase
class RestoreHotelRural.RestoreDatabaseMain
class Utilidades.FormatoDNI
class Utilidades.HabitacionInfo
class Utilidades.MensajeError
class Utilidades.ReservaInfo
class com.zaxxer.hikari.HikariConfig
class com.zaxxer.hikari.HikariDataSource
class java.awt.Toolkit
class java.io.File
class java.io.IOException
class java.io.InputStream
class java.math.BigDecimal
class java.net.URL
class java.sql.Connection
class java.sql.PreparedStatement
class java.sql.ResultSet
class java.sql.SQLException
class java.text.SimpleDateFormat
class java.time.LocalDate
class java.util.ArrayList
class java.util.Date
class java.util.List
class java.util.Properties
class java.util.ResourceBundle
class java.util.function.UnaryOperator
class java.util.logging.Level
class java.util.logging.Logger
class javafx.application.Application
class javafx.application.Platform
class javafx.beans.property.IntegerProperty
class javafx.beans.property.SimpleIntegerProperty
class javafx.beans.property.SimpleStringProperty
class javafx.beans.property.StringProperty
class javafx.collections.FXCollections
class javafx.collections.ObservableList
class javafx.event.ActionEvent
class javafx.fxml.FXMLLoader
class javafx.scene.Node
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.stage.FileChooser
class javafx.stage.Stage
class utilidades.BDUtilidades
class utilidades.ClienteInfo
class utilidades.ConfigLoader
class utilidades.DataSourceManager
class utilidades.UsuarioInfo
@enduml