@startuml
class Utilidades.HabitacionInfo
class Utilidades.MensajeError
class Utilidades.ReservaInfo
class com.zaxxer.hikari.HikariConfig
class com.zaxxer.hikari.HikariDataSource
class java.io.IOException
class java.io.InputStream
class java.math.BigDecimal
class java.sql.Connection
class java.sql.PreparedStatement
class java.sql.ResultSet
class java.sql.SQLException
class java.time.LocalDate
class java.util.ArrayList
class java.util.Date
class java.util.List
class java.util.Properties
class utilidades.BDUtilidades
class utilidades.ClienteInfo
class utilidades.ConfigLoader
class utilidades.DataSourceManager
class utilidades.UsuarioInfo
Utilidades.ReservaInfo ..> java.math.BigDecimal
Utilidades.ReservaInfo ..> java.util.Date
utilidades.BDUtilidades ..> Utilidades.HabitacionInfo
utilidades.BDUtilidades ..> Utilidades.MensajeError
utilidades.BDUtilidades ..> Utilidades.ReservaInfo
utilidades.BDUtilidades ..> java.math.BigDecimal
utilidades.BDUtilidades ..> java.sql.Connection
utilidades.BDUtilidades ..> java.sql.PreparedStatement
utilidades.BDUtilidades ..> java.sql.ResultSet
utilidades.BDUtilidades ..> java.sql.SQLException
utilidades.BDUtilidades ..> java.time.LocalDate
utilidades.BDUtilidades ..> java.util.ArrayList
utilidades.BDUtilidades ..> java.util.List
utilidades.BDUtilidades ..> java.util.Properties
utilidades.ConfigLoader ..> java.io.IOException
utilidades.ConfigLoader ..> java.io.InputStream
utilidades.ConfigLoader ..> java.util.Properties
utilidades.DataSourceManager ..> com.zaxxer.hikari.HikariConfig
utilidades.DataSourceManager ..> com.zaxxer.hikari.HikariDataSource
utilidades.DataSourceManager ..> java.sql.Connection
utilidades.DataSourceManager ..> java.sql.SQLException
utilidades.DataSourceManager ..> java.util.Properties
@enduml